<?php $page_title='Kemahasiswaan'; require_once __DIR__.'/../../config/auth.php';
if(isset($_GET['hapus'])){$s=$pdo->prepare("DELETE FROM kemahasiswaan WHERE id=?");$s->execute([(int)$_GET['hapus']]);header('Location:index.php');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){$id=(int)$_POST['id'];$d=[trim($_POST['kategori']),trim($_POST['judul']),trim($_POST['isi']),$_POST['status']];if($id){$s=$pdo->prepare("UPDATE kemahasiswaan SET kategori=?,judul=?,isi=?,status=? WHERE id=?");$s->execute([...$d,$id]);}else{$s=$pdo->prepare("INSERT INTO kemahasiswaan(kategori,judul,isi,status) VALUES(?,?,?,?)");$s->execute($d);}header('Location:index.php');exit;}
$data=$pdo->query("SELECT * FROM kemahasiswaan ORDER BY created_at DESC")->fetchAll();require __DIR__.'/../../includes/header.php';?>
<div class="page-head"><div><span class="eyebrow">KEMAHASISWAAN</span><h1>Konten Kemahasiswaan</h1><p>Himpunan mahasiswa, UKM, dan informasi kemahasiswaan.</p></div><button class="btn primary" onclick="openModal()">+ Tambah Konten</button></div>
<div class="panel table-panel"><div class="table-wrap"><table><thead><tr><th>Kategori</th><th>Judul</th><th>Status</th><th>Tanggal</th><th>Aksi</th></tr></thead><tbody><?php foreach($data as $d):?><tr><td><?=e($d['kategori'])?></td><td><strong><?=e($d['judul'])?></strong></td><td><span class="badge"><?=e($d['status'])?></span></td><td><?=date('d/m/Y',strtotime($d['created_at']))?></td><td><button class="btn small" onclick='editItem(<?=json_encode($d)?>)'>Edit</button> <a class="btn small danger-text" href="?hapus=<?=$d['id']?>" onclick="return confirm('Hapus?')">Hapus</a></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="modal" id="modal"><div class="modal-box"><div class="modal-head"><h2>Konten Kemahasiswaan</h2><button onclick="closeModal()">×</button></div><form method="post"><input type="hidden" name="id" id="id"><label>Kategori</label><input name="kategori" id="kategori" placeholder="Himpunan Mahasiswa / UKM" required><label>Judul</label><input name="judul" id="judul" required><label>Isi</label><textarea name="isi" id="isi" rows="6"></textarea><label>Status</label><select name="status" id="status"><option>publish</option><option>draft</option></select><div class="modal-actions"><button type="button" class="btn" onclick="closeModal()">Batal</button><button class="btn primary">Simpan</button></div></form></div></div>
<script>function openModal(){modal.classList.add('show')}function closeModal(){modal.classList.remove('show')}function editItem(d){openModal();['id','kategori','judul','isi','status'].forEach(k=>document.getElementById(k).value=d[k]??'')}</script>
<?php require __DIR__.'/../../includes/footer.php';?>
